# Generated by Django 4.2.13 on 2024-07-13 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='subscriber',
            field=models.BooleanField(default=False),
        ),
    ]
