# Generated by Django 4.2.13 on 2024-07-09 20:14

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adCategory', models.CharField(choices=[('TANK', 'Танки'), ('HEAL', 'Хилы'), ('DAMAGE', 'ДД'), ('TRADE', 'Торговцы'), ('GUILD', 'Гилдмастеры'), ('QUEST', 'Квестгиверы'), ('BLACKSMITH', 'Кузнецы'), ('LEATHERWORK', 'Кожевники'), ('ALCHEMY', 'Зельевары'), ('SPELLMASTER', 'Мастера заклинаний')], max_length=20)),
                ('dateCreation', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=128)),
                ('text', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('dateCreation', models.DateTimeField(auto_now_add=True)),
                ('responseAd', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BulletinBoard.ad')),
            ],
        ),
    ]
