# Generated by Django 4.2.13 on 2024-07-09 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BulletinBoard', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='response',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Ожидает рассмотрения'), ('ACCEPTED', 'Принят'), ('REJECTED', 'Отклонен')], default='PENDING', max_length=8),
        ),
    ]
