# Generated by Django 4.2.13 on 2024-07-13 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BulletinBoard', '0003_response_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='response',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Ожидает рассмотрения'), ('ACCEPTED', 'Принят')], default='PENDING', max_length=8),
        ),
    ]
